[features]
seeds = false
[programs.localnet]
coinflip = "B6cP8oy6k2axMwCwgifeAq5BGnzB77nvvTddvtKND5uQ"

[programs.devnet]
coinflip = "B6cP8oy6k2axMwCwgifeAq5BGnzB77nvvTddvtKND5uQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
